### ISSUE TITLE
mu-iam-common stack fails if it has already been deployed in another region

### ISSUE THREAD

**Issue by akuma12** [stelligent/mu#187]
mu-cloudformation-common Role causes stack to fail if it has already been deployed. Tried deploying into us-east-2 region in account where mu had been deployed in us-east-1.

**Comment by cplee** [comment]
@akuma12 do you have any error messages in the cloudformation events when it tried to update the stack?

**Comment by cplee** [comment]
I see the issue...mu is checking for the existence of a stack (which is regional) but is creating named IAM resources (which are global).  

Options:
* include a region name in the IAM resources
* have mu check for the existence of the IAM resource by name, rather than just checking for a CFN stack

**Comment by cplee** [comment]
A workaround would be to use custom namespace for now:

https://github.com/stelligent/mu/wiki/FAQ#how-can-multiple-developers-run-the-same-app-multiple-times-in-the-same-account-without-affecting-each-other

**Comment by akuma12** [comment]
Thanks! I'll try the Namespace option.

**Comment by akuma12** [comment]
So I tried using the namespace option, but it looks like the CodePipeline bucket name doesn't use the namespace, it's still trying to call itself mu-bucket-codepipeline-<accountid>, which causes conflicts.

**Comment by cplee** [comment]
Fixed in 1.0.3 and 1.1.1-devel
