### ISSUE TITLE
`mu` support for EKS / Kubernetes

### ISSUE THREAD

**Issue by timbaileyjones** [stelligent/mu#228]
Would it make sense to extend `mu` into Kubernetes?

New from re:invent 2017: 
https://aws.amazon.com/blogs/aws/amazon-elastic-container-service-for-kubernetes/

EDIT: changed "ECS" to "EKS" in the title

**Comment by cplee** [comment]
duplicate of #233

**Comment by timbaileyjones** [comment]
yes, but 228 came before 233. 💫
