### ISSUE TITLE
Add support for CodeBuild's caching feature 

### ISSUE THREAD

**Issue by timbaileyjones** [stelligent/mu#229]
https://aws.amazon.com/blogs/devops/how-to-enable-caching-for-aws-codebuild (Section 6).

Enable the user to specify the information required for Codebuild caching in the `mu.yml` file. 
 The required parameters would have to include an S3 bucket URL, a path prefix and an IAM role.  These parameters would appear in the CFN template that creates the CodeBuild jobs.

If present, the `buildspec.xml` file would have to be modified by the user to specify the path(s) to cache:
```
cache: 
   paths: 
      #- 'node_modules/**/*'
      #- '.m2/**/*
      #- '.gem/**/*'
```

Codebuild's caching feature works by maintaining a zipfile in an S3 bucket containing these paths.  This shortens the build time, and reduces repetitive connections to these external artifact repositories.

**Comment by cplee** [comment]
Fixed in 1.3.1
