### ISSUE TITLE
Use codepipeline ecs deploy target, rather than cloudformation?

### ISSUE THREAD

**Issue by brentley** [stelligent/mu#266]
I haven't tried it, but I suspect it would speed up the deploy.

**Comment by cplee** [comment]
problem is that it assumes the cluster/service already exists.  it just creates a new task definition and updates service to use it.  plus, it avoid CFN which is a fundamental principle of mu.

**Comment by brentley** [comment]
Yeah, I'm just looking for ways to speed up the deploy time. Also, the codepipeline -> ecs integration is relatively new. (a few weeks?)

It doesn't avoid CFN... that would still be used to setup the codepipeline config, it just wouldn't get used on each deploy.

**Comment by cplee** [comment]
> It doesn't avoid CFN... that would still be used to setup the codepipeline config, it just wouldn't get used on each deploy.
Wouldn't it cause the stack to drift?  The stack would have a different image for the task then what is the actual ECS service

**Comment by brentley** [comment]
I might be missing something, since I haven't set this up... but what I'm thinking is CFN sets up the pipeline still, but the pipeline runs through and deploys the service. 

I should just set this up and see if there is any speed gain in the first place. If not, it's probably not worth the change.

**Comment by brentley** [comment]
So I finally got around to setting this up. The deploy times went from ~10 minutes to ~6 minutes. It's an improvement, but I'm not completely convinced the savings is worth it. 

I'll close this and figure out how to stop watching the pot boil.
