### ISSUE TITLE
is it possible to infer the repo path from the local checkout?

### ISSUE THREAD

**Issue by brentley** [stelligent/mu#268]
I'm thinking about in the case of forking/cloning your own repo, it wouldn't require someone to then immediately edit mu.yml to make it useful.

```  
pipeline:
    source:
      repo: brentley/ecsdemo-backend
```

**Comment by cplee** [comment]
It already does this.  If you leave that out and `mu pipeline up` then the repo is inferred.

Example here: https://github.com/cplee/hello-nginx

**Comment by brentley** [comment]
awesome!
