### ISSUE TITLE
codepipeline may be making unauthenticated calls to github

### ISSUE THREAD

**Issue by brentley** [stelligent/mu#287]
I started seeing rate limiting with my pipelines after updating to 1.4.3. I don't know if this is a code-change problem, or a github problem, but I was able to grab the error before it evaporated:

Rate limit exceeded with: --Response Header-- HttpResponseProxy{HTTP/1.1 403 Forbidden [Server: GitHub.com, Date: Thu, 01 Mar 2018 03:57:32 GMT, Content-Type: application/json; charset=utf-8, Transfer-Encoding: chunked, Status: 403 Forbidden, X-RateLimit-Limit: 60, X-RateLimit-Remaining: 0, X-RateLimit-Reset: 1519876727, X-OAuth-Scopes: admin:repo_hook, repo, X-Accepted-OAuth-Scopes: repo, X-GitHub-Media-Type: github.v3; param=moondragon; format=json, Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, Access-Control-Allow-Origin: *, Content-Security-Policy: default-src 'none', Strict-Transport-Security: max-age=31536000; includeSubdomains; preload, X-Content-Type-Options: nosniff, X-Frame-Options: deny, X-XSS-Protection: 1; mode=block, X-Runtime-rack: 0.037954, X-GitHub-Request-Id: 6C25:698D:25A679A:49D8660:5A977A22] org.apache.http.client.entity.DecompressingEntity@1dab02c7} --Response Body-- {"message":"API rate limit exceeded for user ID 36453127.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

The telling bit is: ` X-RateLimit-Limit: 60` which matches up with the limit they set for unauthenticated calls. 5k is the limit for authenticated calls. 

I manually edited the source step in my codepipelines, and "connected" to my github repos, and the rate limiting went away.

**Comment by cplee** [comment]
What's weird about this is the headers show there is a valid OAuth token as it found scopes in the token:

`X-OAuth-Scopes: admin:repo_hook, repo`

**Comment by brentley** [comment]
yeah, I saw that too... it may be problems on github's side, but since I had re-established the connection manually, and the problem went away I figured I'd go ahead and bring it up.
