### ISSUE TITLE
AccessDenied when directory's name different from repo's name

### ISSUE THREAD

**Issue by ruicosta042** [stelligent/mu#300]
hi, the repo I'm trying `mu` on, has a dash (`-`) in its name, say it's called `MY-PROJECTNAME`. For most of the templates, `mu` uses `PROJECTNAME` as the `ServiceName` - it removes `MY-` from the repo's name.

But, when I try to build the image, I get this error:

```▶ ERROR [0m AccessDenied: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/mu-pipeline-PROJECTNAME-ci-zz-zzzz-n/AWSCodeBuild-abcde123-abcd-abcd-abcd-abcdef123456 is not authorized to perform: cloudformation:CreateStack on resource: arn:aws:cloudformation:zz-zzzz-n:xxxxxxxxxxxx:stack/mu-repo-MY-PROJECTNAME/*```

it can't find `stack/mu-repo-MY-PROJECTNAME` because what `mu` did create is named `stack/mu-repo-PROJECTNAME`.

v1.4.5

**Comment by cplee** [comment]
@ruicosta042 are you able to share your mu.yml file?

**Comment by ruicosta042** [comment]
hey, sure, I believe it takes the `ServiceName` from the directory, not the repo's name, but then for building the image stack it takes the repo's name resulting in a conflict. I made a dummy project here: https://github.com/ruicosta042/one-two-three. You can check out the dry run on the `.mu` folder. That dry run was done a directory called `two-three`, but the repo's name is `one-two-three`

**Comment by ruicosta042** [comment]
https://github.com/ruicosta042/one-two-three/search?utf8=%E2%9C%93&q=two-three&type=

**Comment by mneil** [comment]
possibly related to #318

**Comment by cplee** [comment]
looks like was related to folder name prob identified in #318
