### ISSUE TITLE
How do you handle secret environment variables?

### ISSUE THREAD

**Issue by calvinlfer** [stelligent/mu#307]
For example, you want to provide a Cassandra username and password to an application and want to keep the password hidden/encrypted? The idea is that you are committing your mu.yml file to source control and you don't want to commit the unencrypted password in there as well. 

One approach for working with passwords/secrets was to make use of AWS KMS and build some tooling around it (https://github.com/ukayani/kms-env)

**Comment by timbaileyjones** [comment]
We have used Custom Cloudformation overrides in `mu.yml` to allow secrets in System Manager Parameter Store to be passed to Resources via environment variables.  There is one minor gap, and that is that CFN cannot directly read SecureStrings from Parameter Store.  I used this Lambda/CustomCloudformation Resource to overcome that gap.
   https://github.com/binxio/cfn-secret-provider

Here is what the code sample would look like, after installing cfn-secret-provider.  

    Resources:
        SessionsDatabaseMasterPassword:
            Type: Custom::Secret
            Properties:
                Name: "/database/sessions/master/password"
                Alphabet: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
                Description: "Master Password of Sessions DB"
                Length: 30
                ReturnSecret: true
                Version: v1
                NoEcho: False
                ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-secret-provider'
        SessionsDatabaseCluster:
            Type: AWS::RDS::DBCluster
            Properties:
                MasterUsername: master
                MasterUserPassword:
                    Fn::GetAtt: SessionsDatabaseMasterPassword.Secret

**Comment by mneil** [comment]
Looks like this is resolved. As an update, Cloudformation now supports secure parameters from SSM Parameter Store! https://aws.amazon.com/about-aws/whats-new/2018/08/aws-cloudformation-introduces-dynamic-references-to-support-aws-/
