### ISSUE TITLE
Code pipeline error

### ISSUE THREAD

**Issue by tushariscoolster** [stelligent/mu#312]
Below is the report what is happening in codepipline now,

Whenever someone continually pushes the code to the repository, while the build is in the process in code pipeline,
You get the error in the ECS saying
CannotPullContainerError: API error (404): manifest for XXXXXXXXX.dkr.ecr.us-west-2.amazonaws.com/XXX-frontend:GvR0bMu not found

Probably this is the error in the MU framework, Which try to deploy the image which is not been create while code build.
 In above example, if you find the image in ECR with tag, GvR0bMu, there is no such image with the specific tag

**Comment by cplee** [comment]
@tushariscoolster do you see an image being created in the `Image` action of the build stage?  If so, what tag is on that image?

**Comment by tushariscoolster** [comment]
@cplee  it generated the image with the image tag which is not actually being deployed. so both of them have the separate image tag

**Comment by tushariscoolster** [comment]
Hello @cplee 
did you found out the root cause of this problem?

**Comment by cplee** [comment]
@tushariscoolster i need more info to diagnose.  Can you share the codebuild logs for the image and deploy actions?

**Comment by tushariscoolster** [comment]
@cplee i have added the logs
[000000.log](https://github.com/stelligent/mu/files/2157187/000000.log)
[deploy.log](https://github.com/stelligent/mu/files/2157188/deploy.log)

**Comment by tushariscoolster** [comment]
@cplee  was above logs helpful to debug?

**Comment by cplee** [comment]
@tushariscoolster i see the image that was built was `969064053837.dkr.ecr.us-east-1.amazonaws.com/kqed-frontend:yzGIkS8` but the one deployed was `969064053837.dkr.ecr.us-east-1.amazonaws.com/kqed-frontend:Z1eOnz6`

The tag is coming from the version of the object in S3 bucket that is used as the source artifact for the pipeline.  Do you have 1 pipeline or 2?

**Comment by cplee** [comment]
Ah, sounds like that is the root of the problem.  The second pipeline is not using the same image tag that was built in the first pipeline.
