### ISSUE TITLE
Document param store use, errors, and mitigation

### ISSUE THREAD

**Issue by mneil** [stelligent/mu#345]
If #343 is introduced there is the ability to get into this broken state where the CMK is deleted but the parameter still exists in the param store. If you attempt to relaunch a database using that key you will get an error like:

```
ValidationError: arn:aws:kms:{region}:{accountId}:key/{keyId} is pending deletion. (Service: AWSKMS; Status Code: 400; Error Code: KMSInvalidStateException; Request ID: {id}) (Service: AWSSimpleSystemsManagement; Status Code: 400; Error Code: InvalidKeyId; Request ID: {id})
```

To fix this create a new version of the param using the new key MU created. Or, you can delete the param and let MU generate a new one for us using the correct param.

**Comment by cplee** [comment]
fixed in 4bd2eeca79873e3d616a3891f1dc8d7c3a9e7b61
