### ISSUE TITLE
ECS scheduled tasks broken

### ISSUE THREAD

**Issue by wrkngu0** [stelligent/mu#367]
Hi
It's creating scheduled tasks definition correctly but using own role for events which does not have correct permission for task placement in service. 
Using default `ecsEventsRole` fixes this problem. 
I suggest you to using aws managed policy `arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceEventsRole ` in mu-service-*-events-eu-west-1 role.

**Comment by cplee** [comment]
fixed with #368
