### ISSUE TITLE
Custom CloudFormation results into empty CF template

### ISSUE THREAD

**Issue by AndreyMarchuk** [stelligent/mu#371]
mu v1.5.8

Steps to reproduce:
1. Include local CF extension into mu.yml like so
```
extensions:
  - url: myextension      # points to the subfolder ./myextension
```

2. Create your extension (does not matter what's inside env-ecs.yml)
./myextension/mu-extension.yml
./myextension/env-ecs.yml   

3. Run `mu -d env up dev`

4. RESULT:
/tmp/mu-dryrun/template-mu-environment-devenv.yml is empty

**Comment by cplee** [comment]
fixed with #372
