### ISSUE TITLE
Add ability to link a mu config / project to a specific AWS account

### ISSUE THREAD

**Issue by mattbucci** [stelligent/mu#381]
Maybe there is an existing way to do this but I haven't found a good way.

prior to using mu you must initialize your aws cli with your IAM account using `aws configure` to set my secrets and datacenter, I would propose somehow bundling this step into the mu cli and allowing you to reconfigure this on a per project basis, personally I have 2 different AWS accounts I need to deploy to, one for work and one for personal usage. 

Currently, every time I switch back and forth I must rerun `aws configure` and pass my credentials, forgetting to do this will place my project on the wrong account.

**Comment by brentley** [comment]
I think you want to explore aws cli profiles: https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

And then use them with mu, documented here: https://github.com/stelligent/mu/wiki/CLI-Usage

**Comment by mattbucci** [comment]
Thanks!
