### ISSUE TITLE
KMS.ValidationException when referring to `pipeline` or service

### ISSUE THREAD

**Issue by bciceron** [stelligent/mu#382]
```ERROR KMS.ValidationException: 1 validation error detected: Value '' at 'keyId' failed to satisfy constraint: Member must have length greater than or equal to 1```
this happens when trying to create a simple pipeline like https://github.com/stelligent/mu/tree/develop/examples/pipeline-newman.
i tried adding a "kmsKey:" with a manually created KMS key of my own to no avail, same error.
does mu assume anything about our KMS config ?

**Comment by cplee** [comment]
@bciceron can you provide the steps you took so i can try to reproduce?

**Comment by bciceron** [comment]
cd examples/pipeline-newman
mu env up dev
+-------------+--------------------+------------------+---------------------+
| ENVIRONMENT |       STACK        |      STATUS      |     LAST UPDATE     |
+-------------+--------------------+------------------+---------------------+
| dev         | mu-environment-dev | CREATE_COMPLETE  | 2018-10-31 09:21:16 |
+-------------+--------------------+------------------+---------------------+
mu svc push
09:25:11.068 aws ▶ 047 Creating artifact at 's3://mu-codedeploy-us-west-2-925741509387/banana-service/5296721.zip'
func1 ▶ ERROR  KMS.ValidationException: 1 validation error detected: Value '' at 'keyId' failed to satisfy constraint: Member must have length greater than or equal to 1
	status code: 400, request id: 22F725217364EE97, host id: ...=
09:25:11.322 workflows ▶ 049 KMS.ValidationException: 1 validation error detected: Value '' at 'keyId' failed to satisfy constraint: Member must have length greater than or equal to 1
	status code: 400, request id: 22F725217364EE97, host id: ...=
func1 ▶ ERROR

**Comment by cplee** [comment]
try `mu svc push -p ecr`...the problem is there isn't a `Dockerfile` in that example.  it was intended to be a snippet, not a complete working example.  i should probably fix that...

**Comment by bciceron** [comment]
yes this remove the error, thanks.
