### ISSUE TITLE
ValidationError when updating pipeline

### ISSUE THREAD

**Issue by trevorharwell** [stelligent/mu#391]
I was testing the pipeline feature out and I disabled the acceptance and production pipelines.  Once I was happy with the build, I attempted to enabled the acceptance pipeline.  I then proceeded to run `mu pipeline up` and receive the following error.

`ValidationError: Invalid input for parameter key DatabaseName. Cannot specify usePreviousValue as true for a parameter key not in the previous template`

I found a similar issue in aws-cli that has been fixed: https://github.com/aws/aws-cli/issues/2599

I wonder if it updating the aws-sdk-go could resolve the issue.

**Comment by cplee** [comment]
resolved in 7409129 by avoiding passing database name parameter when empty string
