### ISSUE TITLE
wiki nit: service.protocol is required to be uppercase (eg replace 'http' with 'HTTP')

### ISSUE THREAD

**Issue by srp** [stelligent/mu#403]
Currently the [wiki Services page](https://github.com/stelligent/mu/wiki/Services) shows:

```
service:
  ...
  protocol: http                     # The protocol for the port exposed from the container (default: http)
  ...
```

However, service-ec2.yml and service-ecs.yml only allow `HTTP` and `HTTPS` for ServiceProtocol; attempting to use `http` fails with:

```
ValidationError: Parameter 'ServiceProtocol' must be one of AllowedValues
```

**Comment by cplee** [comment]
fixed.  thanks.
