### ISSUE TITLE
Unable to use ecs-fargate example to create a working service

### ISSUE THREAD

**Issue by masha256** [stelligent/mu#413]
I am just trying to create a service using the out of the box ecs-fargate example with zero changes so I can see all the pieces working.  I successfully created the environment using:

```mu env up production```

And then built the Docker image/uploaded to ECR with:

```mu service push```

Next, I tried to create the ECS service using:

```mu service deploy production```

But get an error around CPUUtilizationPolicyTarget, which seems to be when the cloudformation template attempts to create the auto scaling groups. Perhaps some defaults around ECS Fargate have changed since it was originally written? 

Full Log:

```
Mikes-MacBook-Pro-4:ecs-fargate machado$ mu service deploy production
Dockerfile found, assuming ECR pipeline
Upserting IAM resources
  No changes for stack 'mu-iam-common'
  No changes for stack 'mu-iam-service-ecs-fargate-example-production'
Upsert repo for service 'ecs-fargate-example'
  No changes for stack 'mu-repo-ecs-fargate-example'
Deploying service 'ecs-fargate-example' to 'production' from '1418REDACTED1234.dkr.ecr.us-west-1.amazonaws.com/mu-ecs-fargate-example:e3cddf5'
  Stack 'mu-service-ecs-fargate-example-production' was in 'ROLLBACK_COMPLETE' status, deleting...
  Deleted stack 'mu-service-ecs-fargate-example-production'
  Created stack 'mu-service-ecs-fargate-example-production'
/  mu-service-ecs-fargate-example-production:  EcsService (AWS::ECS::Service) CREATE_IN_PROGRESS Resource creation Initiated logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
\  mu-service-ecs-fargate-example-production:  mu-service-ecs-fargate-example-production (AWS::CloudFormation::Stack) ROLLBACK_IN_PROGRESS The following resource(s) failed to create: [CPUUtilizationPolicyTarget]. . Rollback requested by user. logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
-  mu-service-ecs-fargate-example-production:  mu-service-ecs-fargate-example-production (AWS::CloudFormation::Stack) ROLLBACK_IN_PROGRESS The following resource(s) failed to create: [CPUUtilizationPolicyTarget]. . Rollback requested by user. logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
-  mu-service-ecs-fargate-example-production:  EcsService (AWS::ECS::Service) DELETE_IN_PROGRESS  logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
\  mu-service-ecs-fargate-example-production:  EcsService (AWS::ECS::Service) DELETE_IN_PROGRESS  logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
\  mu-service-ecs-fargate-example-production:  EcsService (AWS::ECS::Service) DELETE_IN_PROGRESS  logEventStatus ▶ ERROR    mu-service-ecs-fargate-example-production:  CPUUtilizationPolicyTarget (AWS::ApplicationAutoScaling::ScalableTarget) CREATE_FAILED ECS service doesn't exist: service/mu-environment-production/mu-environment-production (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: d1782e3c-00dc-11e9-9665-0d5040a45004)
/  mu-service-ecs-fargate-example-production:  EcsService (AWS::ECS::Service) DELETE_IN_PROGRESS
.
.
func1 ▶ ERROR  Ended in failed status ROLLBACK_COMPLETE
func1 ▶ ERROR
```

**Comment by srp** [comment]
For what it's worth I just ran the above commands in the `examples/ecs-fargate` directory and wasn't able to reproduce the problem. I have very little experience with this, but the "CREATE_FAILED ECS service doesn't exist" part makes me think that the ecs service, which should have been started as part of `mu env up production`, either failed to start or otherwise was not still running by the time the last command was run.

**Comment by cplee** [comment]
@machadolab I also just tried this and was unable to reproduce.  I even tried in us-west-1 hoping for something weird with that region. Are you able to review the events for the `mu-service-ecs-fargate-example-production` stack?  i agree with @srp that the problem is likely with a resource that failed earlier and the error didn't get logged properly by mu.

**Comment by masha256** [comment]
Should a “mu env up production” create the service? Shouldn’t it be created at the time the service is deployed? If the env up should create it, then yeah, it isn’t getting created. I’ll check the CF stack and get back to you. Thanks for checking it out!! 😎

**Comment by masha256** [comment]
Here is a screenshot of the `mu-service-ecs-fargate-example-production` stack log:

<img width="1385" alt="screenshot 2018-12-18 08 39 27" src="https://user-images.githubusercontent.com/1002843/50168525-7c99fc00-02a0-11e9-9bad-a1df432e7fdd.png">

If I am reading it correctly, looks like its trying to create a service name called

`service/mu-environment-production/mu-service-ecs-fargate-example-production-EcsService-GZBYNY7PMK3I`

And the rest of the stack template is expecting `service/mu-environment-production/mu-service-ecs-fargate-example-production`?

**Comment by cplee** [comment]
Weird.  It looks like it is trying to reference an invalid service name on the auto scaling target:  `service/mu-environment-production/mu-environment-production`.

Can you run in dryrun via `mu -d service deploy production` and then share the CFN template and param files from $TMPDIR/mu-dryrun

**Comment by masha256** [comment]
[mu_debug.zip](https://github.com/stelligent/mu/files/2691637/mu_debug.zip)

templates and json params attached in the .zip.

Just had a thought. I did opt into the new ARN and Resource ID format as prompted by this:

<img width="1178" alt="screenshot 2018-12-18 09 44 42" src="https://user-images.githubusercontent.com/1002843/50172318-a4da2880-02a9-11e9-8068-be904259fc5c.png">

Could that have something to do with the naming mismatch?

**Comment by masha256** [comment]
Sure enough, reverted back to the old format and `mu service deploy production` succeeded!

**Comment by cplee** [comment]
Thanks Mike, i've created a new issue #414 to capture this bug.
