### ISSUE TITLE
New ARN and Resource ID for ECS causes deploy failure

### ISSUE THREAD

**Issue by cplee** [stelligent/mu#414]
![image](https://user-images.githubusercontent.com/2239057/50173602-d6a0be80-02ac-11e9-8662-bcacda1ce133.png)

**Comment by cplee** [comment]
fixed with #415

**Comment by karlskidmore** [comment]
Any chance this fix could be merged to master and a release made?  The deadline for adopting the new ARN format is fast approaching.
